packaging_format = 2

id = "textpad"
name = "TextPad"
description.en = "A simple online notepad, no WYSIWYG, no fancy stuff, just write."

version = "0.1~ynh1"

maintainers = [ghose]

[upstream]
license = "The MIT License"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "1M"
ram.build = "5M"
ram.runtime = "0M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/site"

    [install.init_main_permission]
    type = "group"
    default = "visitors"


[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
